_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 53ec6a10-317d-46b8-a2d8-41ee08ce3352
name: 'Colorado Judicial Branch'
mail: akempler@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
